<table>

    <tr>

        <th><?php echo $this->translate("Title") ?></th>

        <th><?php echo $this->translate("Artist") ?></th>

        <th><a href="<?php echo $this->url('album', array('action' => 'add')); ?>"><?php echo $this->translate("Add new album") ?></a></th>

    </tr>

    <?php foreach ($albums as $album) : ?>

        <tr>

            <td><?php echo $this->escapeHtml($album->title); ?></td>

            <td><?php echo $this->escapeHtml($album->artist); ?></td>

            <td>

                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id));?>">Edit</a>

                <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id));?>">Delete</a>

            </td>

        </tr>

    <?php endforeach; ?>

</table>